CXX=mpixlcxx_r
CFLAGS=-qsmp=omp -qarch=450d -qtune=450 -O5
EXECUTABLE=task2bg.exe
LD=

all: Comparator.o Schedule.o Point.o
	$(CXX) $(CFLAGS) -o $(EXECUTABLE) Comparator.o Schedule.o Point.o main.cpp $(LD)

Comparator.o:
	$(CXX) -c $(CFLAGS) -o Comparator.o Comparator.cpp

Schedule.o:
	$(CXX) -c $(CFLAGS) -o Schedule.o Schedule.cpp

Point.o:
	$(CXX) -c $(CFLAGS) -o Point.o Point.cpp

testdhsort:
	g++ -Wall test_dhsort.cpp -o testdhsort $(LD)

clean:
	rm -rf *.o testdhsort
